services:
  backend:
    build:
      context: ./backend
    container_name: simple-workflow-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    container_name: simple-workflow-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
